spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clinicDB?createDatabaseIfNotExist=true
    username: root
    password: root
  application:
    name: clinic-services

server:
  port: 8600